export const SET_VERSION = 'SET_VERSION';
export const SET_VERSION_ERROR = 'SET_VERSION_ERROR';
export const SET_LINK_LIST = 'SET_LINK_LIST';
export const SET_LINK_LIST_ERROR = 'SET_LINK_LIST_ERROR';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_PRINCIPAL = 'SET_PRINCIPAL';
export const SET_PRINCIPAL_ERROR = 'SET_PRINCIPAL_ERROR';
export const CLEAR_STATE = 'CLEAR_STATE';